### ISSUE TITLE
Doesn't Build

### ISSUE THREAD

**Issue by Hackmodford** [keaganhilliard/audiobookly#1]
I cloned the repo and tried to build. It complains it's missing CupertinoListTile

**Comment by Hackmodford** [comment]
This seemed to be the answer.
`flutter channel master && flutter upgrade`
https://davidserrano.io/cupertino-lists-the-missing-widgets-from-the-flutter-cupertino-collection

**Comment by Hackmodford** [comment]
Previous answer caused other issues. I had to use this package.
https://pub.dev/packages/cupertino_lists/install

**Comment by keaganhilliard** [comment]
Hmm... what other issues did it cause? I'm running flutter master and it works fine

**Comment by Hackmodford** [comment]
Something regarding a bottom modal dialogue if I remember right.

**Comment by keaganhilliard** [comment]
interesting, I might just switch to use that list tile instead and go back to stable.
